dist: xenial
sudo: required
language: python
node_js:
  - "9.4.0"

python:
  - "3.6"

cache:
  directories:
  - $HOME/.ethash
  - backend/travisCI/datadir/geth/ethash

matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
      - sudo add-apt-repository ppa:ethereum/ethereum -y
      - sudo apt-get update
      - sudo apt-get install build-essential -y
      - sudo apt-get install gcc g++ libssl-dev libudev-dev pkg-config
      - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - rm -rf node_modules
      - echo "finish node_modules"
      - sudo apt-get install software-properties-common -y -qq
      - sudo add-apt-repository ppa:ethereum/ethereum-dev -y
      - sudo apt-get update
      - sudo apt-get install geth -y

install:
  - bash ./solidity/bin/travis-install.sh
  - bash ./backend/travisCI/travis-install.sh

script:
  - bash ./solidity/bin/test.sh
  - bash ./backend/travisCI/test.sh
